export type D1ServerTemplateParams = {
	schemaImportPath: string;
	configImportLine: string;
	handlerImports: string[];
	authImports: string;
	authSetupBlock: string;
	authMountBlock: string;
	authResolverBlock: string;
	routeLines: string[];
	httpLines: string[];
	/** Import path for the generated Prisma client (e.g., "../prisma/client") */
	prismaClientImportPath: string;
};

export function renderD1ServerTemplate(params: D1ServerTemplateParams): string {
	const authImportBlock = params.authImports ? `\n${params.authImports}\n` : "";
	const handlerImportBlock = params.handlerImports.join("\n");

	return `/* eslint-disable */
/**
 * This file is auto-generated by appflare/handler-build.ts.
 * Do not edit directly.
 */

import { Hono } from "hono";
import type { Context as HonoContext } from "hono";
import { sValidator } from "@hono/standard-validator";
import { z } from "zod";
import { cors } from "hono/cors";
import schema from ${JSON.stringify(params.schemaImportPath)};
${params.configImportLine}
import { PrismaClient } from ${JSON.stringify(params.prismaClientImportPath)};
import { PrismaD1 } from "@prisma/adapter-d1";
import {
	createR2StorageManager,
	type StorageManagerOptions,
} from "appflare/server/storage";${authImportBlock}
import type {
	AppflareAuthContext,
	AppflareAuthSession,
	AppflareAuthUser,
	TableDocMap,
	TableNames,
	Scheduler,
} from "../src/schema-types";

${handlerImportBlock}

export type AppflareDbContext = PrismaClient;

export type AppflareServerContext = AppflareAuthContext & {
	db: AppflareDbContext;
	scheduler?: Scheduler;
	error: AppflareErrorFactory;
};

export type AppflareHandlerError = Error & {
	status: number;
	details?: unknown;
	__appflareHandlerError: true;
};

export type AppflareErrorFactory = (
	status: number,
	message?: string,
	details?: unknown
) => AppflareHandlerError;

const createHandlerError: AppflareErrorFactory = (
	status,
	message,
	details
) => {
	const err = new Error(message ?? \`HTTP \${status}\`);
	err.name = "AppflareHandlerError";
	const typed = err as AppflareHandlerError;
	typed.status = status;
	typed.details = details;
	typed.__appflareHandlerError = true;
	return typed;
};

const isHandlerError = (value: unknown): value is AppflareHandlerError =>
	!!value &&
	typeof value === "object" &&
	(value as any).__appflareHandlerError === true &&
	Number.isFinite((value as any).status);

const handlerErrorBody = (
	err: AppflareHandlerError
): { error: string; details?: unknown } => {
	const includeDetails =
		err.details !== undefined &&
		(err.details && typeof err.details === "object"
			? !(err.details instanceof Error) && !Array.isArray(err.details)
			: true);
	return includeDetails
		? { error: err.message, details: err.details }
		: { error: err.message };
};

async function runHandlerWithMiddleware<TArgs, TResult>(
	handler: {
		handler: (ctx: AppflareServerContext, args: TArgs) => Promise<TResult>;
		middleware?: (
			ctx: AppflareServerContext,
			args: TArgs
		) => Promise<TResult | void>;
	},
	ctx: AppflareServerContext,
	args: TArgs
): Promise<TResult> {
	if (handler.middleware) {
		const middlewareResult = await handler.middleware(ctx, args);
		if (typeof middlewareResult !== "undefined") {
			return middlewareResult as TResult;
		}
	}
	return handler.handler(ctx, args);
}

export function createAppflareDbContext(params: {
	d1: D1Database;
}): AppflareDbContext {
	const adapter = new PrismaD1(params.d1);
	return new PrismaClient({ adapter });
}

export type MutationNotification = {
	table: TableNames;
	handler: { file: string; name: string };
	args: unknown;
	result: unknown;
};

type DurableObjectNamespaceLike = {
	idFromName(name: string): any;
	get(id: any): { fetch(input: any, init?: RequestInit): Promise<Response> };
};

type MutationNotifier = (payload: MutationNotification) => Promise<void>;

type RealtimeOptions = {
	notify?: MutationNotifier;
	durableObject?: DurableObjectNamespaceLike;
	durableObjectName?: string;
};

type StorageOptions<Env = unknown, Principal = unknown> =
	Partial<StorageManagerOptions<Env, Principal>> & {
		enabled?: boolean;
		corsOrigin?: string | string[];
		corsAllowHeaders?: string[];
		corsAllowMethods?: string[];
	};

export type AppflareHonoServerOptions = {
	/** Provide a static D1 database binding. If omitted, set getD1 instead. */
	d1?: D1Database;
	/** Provide a per-request D1 database binding (e.g. from Cloudflare env bindings). */
	getD1?: (c: HonoContext) => D1Database | Promise<D1Database>;
	/** Provide a scheduler instance for enqueueing background work. */
	scheduler?: Scheduler;
	/** Provide a per-request scheduler instance (e.g. derived from env bindings). */
	getScheduler?: (c: HonoContext) => Scheduler | Promise<Scheduler>;
	/** Optionally extend the context beyond the db wrapper. */
	createContext?: (
		c: HonoContext,
		db: AppflareDbContext,
		auth: AppflareAuthContext,
		scheduler?: Scheduler,
		error?: AppflareErrorFactory
	) => AppflareServerContext | Promise<AppflareServerContext>;
	corsOrigin?: string | string[];
	realtime?: RealtimeOptions;
	storage?: StorageOptions;
};

function normalizeTableName(table: string): TableNames {
	const tables = schema as Record<string, unknown>;
	if (tables[table]) return table as TableNames;
	const plural = table + "s";
	if (tables[plural]) return plural as TableNames;
	throw new Error("Unknown table: " + table);
}

function normalizeStorageBasePath(basePath?: string): string {
	if (!basePath) return "/storage";
	const withLeadingSlash = basePath.startsWith("/")
		? basePath
		: "/" + basePath;
	return withLeadingSlash.endsWith("/")
		? withLeadingSlash.slice(0, -1) || "/"
		: withLeadingSlash;
}

function formatHandlerError(err: unknown): {
	status: number;
	body: { error: string; details?: unknown };
} {
	if (isHandlerError(err)) {
		return { status: err.status, body: handlerErrorBody(err) };
	}
	const statusCandidate =
		typeof err === "object" && err !== null
			? Number((err as any).status ?? (err as any).statusCode)
			: undefined;
	const status = Number.isFinite(statusCandidate)
		? Number(statusCandidate)
		: 500;

	const message =
		err instanceof Error
			? err.message
			: typeof err === "string"
				? err
				: "Unknown error";
	const includeDetails =
		err && typeof err === "object" && !(err instanceof Error) && !Array.isArray(err);

	return {
		status,
		body: includeDetails ? { error: message, details: err } : { error: message },
	};
}

export function createAppflareHonoServer(options: AppflareHonoServerOptions): Hono {
	const fixedDb =
		options.d1 &&
		createAppflareDbContext({
			d1: options.d1,
		});

	if (!fixedDb && !options.getD1) {
		throw new Error(
			"AppflareHonoServer requires either options.d1 or options.getD1 to initialize the database context."
		);
	}

	const resolveDb = async (c: HonoContext): Promise<AppflareDbContext> => {
		if (fixedDb) return fixedDb;
		const d1 = await options.getD1!(c);
		return createAppflareDbContext({ d1 });
	};

	const fixedScheduler = options.scheduler;
	const resolveScheduler = async (
		c: HonoContext
	): Promise<Scheduler | undefined> => {
		if (fixedScheduler) return fixedScheduler;
		if (!options.getScheduler) return undefined;
		return options.getScheduler(c);
	};

	const createContext =
		options.createContext ??
		((_c, db, auth, scheduler, error) =>
			({
				db,
				scheduler,
				error: error ?? createHandlerError,
				...auth,
			} as AppflareServerContext));
	const notifyMutation = createMutationNotifier(options.realtime);
	const app = new Hono();
	app.use(
		cors({
			origin: options.corsOrigin ?? "*",
		})
	);

	const storageOptions = options.storage ?? {};
	const storageConfig = (appflareConfig as any).storage;
	const storageRules = storageOptions.rules ?? storageConfig?.rules;
	const storageEnabled =
		(storageOptions.enabled ?? true) && !!storageRules && storageRules.length > 0;

	if (storageEnabled) {
		const storageBasePath = normalizeStorageBasePath(
			storageOptions.basePath ?? storageConfig?.basePath
		);
		const storageManager = createR2StorageManager({
			basePath: storageBasePath,
			bucketBinding:
				storageOptions.bucketBinding ??
				storageConfig?.bucketBinding ??
				"APPFLARE_STORAGE",
			defaultCacheControl:
				storageOptions.defaultCacheControl ??
				storageConfig?.defaultCacheControl,
			getBucket: storageOptions.getBucket ?? storageConfig?.getBucket,
			rules: storageRules!,
		});

		app.use(
			storageBasePath + "/*",
			cors({
				origin: storageOptions.corsOrigin ?? "*",
				allowHeaders: storageOptions.corsAllowHeaders ?? ["*"],
				allowMethods:
					storageOptions.corsAllowMethods ?? [
						"GET",
						"HEAD",
						"PUT",
						"POST",
						"DELETE",
						"OPTIONS",
					],
			}),
		);

		app.route("/", storageManager);
	}
${params.authSetupBlock}${params.authMountBlock}${params.authResolverBlock}	const resolveContext = async (
		c: HonoContext
	): Promise<AppflareServerContext> => {
		const db = await resolveDb(c);
		const auth = await resolveAuthContext(c);
		const scheduler = await resolveScheduler(c);
		const error = createHandlerError;
		const ctx = await createContext(c, db, auth, scheduler, error);
		const merged = {
			db,
			scheduler,
			...auth,
			...(ctx ?? {}),
			error: (ctx as any)?.error ?? error,
		};
		return merged as AppflareServerContext;
	};

		${params.routeLines.join("\n\n\t")}

	${params.httpLines.join("\n\n\t")}

	return app;
}

function createMutationNotifier(
	options?: RealtimeOptions
): MutationNotifier | undefined {
	if (!options) return undefined;
	if (options.notify) return options.notify;
	if (options.durableObject) {
		return async (payload: MutationNotification) => {
			const id = options.durableObject!.idFromName(
				options.durableObjectName ?? "primary"
			);
			const stub = options.durableObject!.get(id);
			await stub.fetch("http://appflare-realtime/notify", {
				method: "POST",
				headers: { "content-type": "application/json" },
				body: JSON.stringify(payload),
			});
		};
	}
	return undefined;
}

`;
}
