/* eslint-disable */
/**
 * This file is auto-generated by appflare/build.ts.
 * Do not edit directly.
 */
type SchemaValidator<TValue> = {
	parse: (value: unknown) => TValue;
};

export type AnyValidator = SchemaValidator<unknown>;

export type TableNames = 'messages' | 'users';

export type Id<TableName extends string> = string & { __table?: TableName };

export interface MessagesDoc {
	_id: Id<'messages'>;
	_creationTime: number;
	body: string;
	user: Id<'users'>;
}

export interface UsersDoc {
	_id: Id<'users'>;
	_creationTime: number;
	name: string;
	tokenIdentifier: string;
}

export interface TableDocMap {
	'messages': MessagesDoc;
	'users': UsersDoc;
}

export type Doc<TableName extends TableNames> = TableDocMap[TableName];

export interface DatabaseQuery<TableName extends TableNames> {
	collect(): Promise<Array<TableDocMap[TableName]>>;
}

export interface DatabaseReader {
	query<TableName extends TableNames>(table: TableName): DatabaseQuery<TableName>;
}

export interface QueryContext {
	db: DatabaseReader;
}

export type QueryArgsShape = Record<string, AnyValidator>;

type InferValidator<TValidator> = TValidator extends SchemaValidator<infer TValue> ? TValue : never;

export type InferQueryArgs<TArgs extends QueryArgsShape> = {
	[Key in keyof TArgs]: InferValidator<TArgs[Key]>;
};

export interface QueryDefinition<TArgs extends QueryArgsShape, TResult> {
	args: TArgs;
	handler: (ctx: QueryContext, args: InferQueryArgs<TArgs>) => Promise<TResult>;
}

export const query = <TArgs extends QueryArgsShape, TResult>(definition: QueryDefinition<TArgs, TResult>): QueryDefinition<TArgs, TResult> => definition;

export const tableIndexes = {
	  "messages": [],
	  "users": [
	    {
	      "name": "by_token",
	      "fields": [
	        "tokenIdentifier"
	      ]
	    }
	  ]
	} as const;
