/* eslint-disable */
/**
 * This file is auto-generated by appflare/db-build.ts.
 * Do not edit directly.
 */
type SchemaValidator<TValue> = {
	parse: (value: unknown) => TValue;
};

export type AnyValidator = SchemaValidator<unknown>;

export type TableNames = "messages" | "users" | "demo";

export type Id<TableName extends string> = string & { __table?: TableName };

export interface MessagesDoc {
	_id: Id<"messages">;
	_creationTime: number;
	body: string;
	user: Id<"users">;
}

export interface UsersDoc {
	_id: Id<"users">;
	_creationTime: number;
	name: string;
	tokenIdentifier: string;
}

export interface DemoDoc {
	_id: Id<"demo">;
	_creationTime: number;
	title: string;
	description?: string;
}

export interface TableDocMap {
	messages: MessagesDoc;
	users: UsersDoc;
	demo: DemoDoc;
}

export type Doc<TableName extends TableNames> = TableDocMap[TableName];

export interface DatabaseQuery<TableName extends TableNames> {
	collect(): Promise<Array<TableDocMap[TableName]>>;
}

export interface DatabaseReader {
	query<TableName extends TableNames>(
		table: TableName
	): DatabaseQuery<TableName>;
}

export interface QueryContext {
	db: DatabaseReader;
}

export type QueryArgsShape = Record<string, AnyValidator>;

type InferValidator<TValidator> =
	TValidator extends SchemaValidator<infer TValue> ? TValue : never;

export type InferQueryArgs<TArgs extends QueryArgsShape> = {
	[Key in keyof TArgs]: InferValidator<TArgs[Key]>;
};

export interface QueryDefinition<TArgs extends QueryArgsShape, TResult> {
	args: TArgs;
	handler: (ctx: QueryContext, args: InferQueryArgs<TArgs>) => Promise<TResult>;
}

export const query = <TArgs extends QueryArgsShape, TResult>(
	definition: QueryDefinition<TArgs, TResult>
): QueryDefinition<TArgs, TResult> => definition;

export type EditableDoc<TableName extends TableNames> = Omit<
	TableDocMap[TableName],
	"_id" | "_creationTime"
>;

export interface DatabaseWriter extends DatabaseReader {
	insert<TableName extends TableNames>(
		table: TableName,
		value: EditableDoc<TableName>
	): Promise<Id<TableName>>;
	patch<TableName extends TableNames>(
		table: TableName,
		id: Id<TableName>,
		partial: Partial<EditableDoc<TableName>>
	): Promise<void>;
	delete<TableName extends TableNames>(
		table: TableName,
		id: Id<TableName>
	): Promise<void>;
}

export interface MutationContext {
	db: DatabaseWriter;
}

export interface MutationDefinition<TArgs extends QueryArgsShape, TResult> {
	args: TArgs;
	handler: (
		ctx: MutationContext,
		args: InferQueryArgs<TArgs>
	) => Promise<TResult>;
}

export const mutation = <TArgs extends QueryArgsShape, TResult>(
	definition: MutationDefinition<TArgs, TResult>
): MutationDefinition<TArgs, TResult> => definition;

export const tableIndexes = {
	messages: [],
	users: [],
	demo: [],
} as const;
