/* eslint-disable */
/**
 * This file is auto-generated by appflare/build.ts.
 * Do not edit directly.
 */
import { query } from '../schema-types';

export const listUsers = query({
	args: {},
	handler: async (ctx) => {
		return ctx.db.query('users').collect();
	},
});
