/* eslint-disable */
/**
 * This file is auto-generated by appflare/db-build.ts.
 * Do not edit directly.
 */
import { z } from "zod";
import {
	mutation,
	query,
	type EditableDoc,
	type Id,
	type QuerySort,
	type QueryWhere,
} from "../schema-types";

export const findUsers = query({
	args: {
		where: z.custom<QueryWhere<"users">>().optional(),
		sort: z.custom<QuerySort<"users">>().optional(),
		limit: z.number().int().nonnegative().optional(),
		offset: z.number().int().nonnegative().optional(),
	},
	handler: async (ctx, args) => {
		let q = ctx.db.query("users" as any);
		if (args.where) q = q.where(args.where as any);
		if (args.sort) q = q.sort(args.sort as any);
		if (args.offset !== undefined) q = q.offset(args.offset);
		if (args.limit !== undefined) q = q.limit(args.limit);
		return q.find();
	},
});

export const findOneUsers = query({
	args: {
		where: z.custom<QueryWhere<"users">>().optional(),
		sort: z.custom<QuerySort<"users">>().optional(),
		offset: z.number().int().nonnegative().optional(),
	},
	handler: async (ctx, args) => {
		let q = ctx.db.query("users" as any);
		if (args.where) q = q.where(args.where as any);
		if (args.sort) q = q.sort(args.sort as any);
		if (args.offset !== undefined) q = q.offset(args.offset);
		return q.findOne();
	},
});

export const insertUsers = mutation({
	args: {
		value: z.custom<EditableDoc<"users">>(),
	},
	handler: async (ctx, args) => {
		return ctx.db.insert("users" as any, args.value as any);
	},
});

export const updateUsers = mutation({
	args: {
		id: z.custom<Id<"users">>(),
		partial: z.custom<Partial<EditableDoc<"users">>>(),
	},
	handler: async (ctx, args) => {
		if (typeof (ctx.db as any).update === "function") {
			await (ctx.db as any).update(
				"users" as any,
				args.id as any,
				args.partial as any
			);
			return;
		}
		await ctx.db.patch(
			"users" as any,
			args.id as any,
			args.partial as any
		);
	},
});

export const deleteUsers = mutation({
	args: {
		id: z.custom<Id<"users">>(),
	},
	handler: async (ctx, args) => {
		await ctx.db.delete("users" as any, args.id as any);
	},
});
