export const schemaTypesImportPath = "../src/schema-types";
export const serverImportPath = "./server";

export const filePreamble = `/* eslint-disable */
/**
 * This file is auto-generated by appflare/handler-build.ts.
 * Do not edit directly.
 */`;
