import { buildImportSection } from "../generate-hono-server/imports";
import type { DiscoveredHandler } from "../../utils/utils";

const schemaTypesImportPath = "../src/schema-types";
const serverImportPath = "./server";

const buildHandlerEntries = (params: {
	handlers: DiscoveredHandler[];
	localNameFor: (handler: DiscoveredHandler) => string;
}): string => {
	if (params.handlers.length === 0) return "";

	return params.handlers
		.map((handler) => {
			const local = params.localNameFor(handler);
			const task = `${handler.fileName}/${handler.name}`;
			return (
				`\t${JSON.stringify(task)}: {\n` +
				`\t\tfile: ${JSON.stringify(handler.fileName)},\n` +
				`\t\tname: ${JSON.stringify(handler.name)},\n` +
				`\t\trun: ${local}.handler,\n` +
				`\t},`
			);
		})
		.join("\n");
};

export function generateSchedulerHandlers(params: {
	handlers: DiscoveredHandler[];
	outDirAbs: string;
	schemaPathAbs: string;
	configPathAbs: string;
}): string {
	const schedulerHandlers = params.handlers.filter(
		(handler) => handler.kind === "scheduler"
	);

	const imports = buildImportSection({
		handlers: schedulerHandlers,
		outDirAbs: params.outDirAbs,
		schemaPathAbs: params.schemaPathAbs,
		configPathAbs: params.configPathAbs,
	});

	const handlerImportBlock =
		imports.handlerImports.length > 0
			? `${imports.handlerImports.join("\n")}\n\n`
			: "";

	const handlerEntries = buildHandlerEntries({
		handlers: schedulerHandlers,
		localNameFor: imports.localNameFor,
	});

	return `/* eslint-disable */
/**
 * This file is auto-generated by appflare/handler-build.ts.
 * Do not edit directly.
 */

import { createAppflareDbContext, type AppflareDbContext } from ${JSON.stringify(serverImportPath)};
import type {
\tScheduler,
\tAppflareAuthContext,
\tAppflareAuthSession,
\tAppflareAuthUser,
} from ${JSON.stringify(schemaTypesImportPath)};
import { getDatabase } from "cloudflare-do-mongo";
import { Db } from "mongodb";
${handlerImportBlock}const schedulerHandlers = {
${handlerEntries}
} as const;

type SchedulerTaskName = keyof typeof schedulerHandlers extends never
	? string
	: keyof typeof schedulerHandlers;

type SchedulerQueueMessage = {
\ttask: SchedulerTaskName | string;
\tpayload?: unknown;
};

type Env = {
\tMONGO_DB: unknown;
\tAPPFLARE_SCHEDULER_QUEUE?: {
\t\tsend: (body: unknown, options?: { delaySeconds?: number }) => Promise<void>;
\t};
} & Record<string, unknown>;

const emptyAuthContext: AppflareAuthContext = {
\tsession: null as AppflareAuthSession,
\tuser: null as AppflareAuthUser,
};

type SchedulerHandlerContext = AppflareAuthContext & {
\tdb: AppflareDbContext;
\tscheduler: Scheduler;
\tenv: Env;
};

export const createScheduler = (
\tqueue?: Env["APPFLARE_SCHEDULER_QUEUE"]
): Scheduler => ({
\tenqueue: async (task, payload, options) => {
\t\tif (!queue) {
\t\t\tthrow new Error("Scheduler queue binding is not configured");
\t\t}
\t\tawait queue.send({ task, payload }, options);
\t},
});

export async function handleSchedulerBatch(params: {
\tbatch: { messages: Array<{ body: unknown }> };
\tenv: Env;
}): Promise<void> {
\tconst { env, batch } = params;
\tif (!env.APPFLARE_SCHEDULER_QUEUE) {
\t\tconsole.warn("Scheduler queue binding missing; skipping batch");
\t\treturn;
\t}

\tconst db = createAppflareDbContext({
\t\tdb: getDatabase(env.MONGO_DB) as unknown as Db,
\t});
\tconst scheduler = createScheduler(env.APPFLARE_SCHEDULER_QUEUE);
\tconst baseContext: SchedulerHandlerContext = {
\t\t...emptyAuthContext,
\t\tdb,
\t\tscheduler,
\t\tenv,
\t};

\tfor (const message of batch.messages ?? []) {
\t\tconst body = (message ?? {}).body as SchedulerQueueMessage;
		const task = body?.task as SchedulerTaskName;
		const handler = (schedulerHandlers as Record<string, { run: (ctx: SchedulerHandlerContext, payload: unknown) => Promise<void> }>)[task as string];
\t\tif (!task || !handler) {
\t\t\tconsole.warn("Skipping scheduler task", task);
\t\t\tcontinue;
\t\t}

\t\ttry {
\t\t\tawait handler.run(baseContext, body?.payload);
\t\t} catch (err) {
\t\t\tconsole.error("Scheduler task failed", task, err);
\t\t}
\t}
}

export type { SchedulerTaskName };
`;
}
