import { resolveAllowedOrigins } from "./helpers";

export function generateCloudflareWorkerIndex(params: {
	allowedOrigins?: string[];
}): string {
	const allowedOrigins = resolveAllowedOrigins(params.allowedOrigins);
	const allowedOriginsCsv = allowedOrigins.join(",");

	return `/* eslint-disable */
/**
 * This file is auto-generated by the Appflare CLI.
 * Do not edit directly.
 */

import { createAppflareHonoServer } from "./server";
import { WebSocketHibernationServer } from "./websocket-hibernation-server";
import { getDatabase } from "cloudflare-do-mongo";
import { MONGO_DURABLE_OBJECT } from "cloudflare-do-mongo/do";
import type { Hono } from "hono";
import { cors } from "hono/cors";
import { Db } from "mongodb";

type DurableObjectNamespaceLike = {
	idFromName(name: string): any;
	get(id: any): { fetch(input: any, init?: RequestInit): Promise<Response> };
};

type Env = {
	MONGO_DB: unknown;
	MONGO_URI?: string;
	WEBSOCKET_HIBERNATION_SERVER: DurableObjectNamespaceLike;
	MONGO_DURABLE_OBJECT: DurableObjectNamespaceLike;
	APPFLARE_STORAGE?: unknown;
	ALLOWED_ORIGINS?: string;
};

type WorkerEnv = { Bindings: Env };

const parseAllowedOrigins = (value?: string | null): string[] =>
	(value ?? ${JSON.stringify(allowedOriginsCsv)})
		.split(",")
		.map((origin) => origin.trim())
		.filter(Boolean);

const resolveCorsOrigin = (
	origin: string | null,
	allowed: string[]
): string | undefined => {
	if (!origin) return undefined;
	if (allowed.includes("*")) return origin;
	return allowed.includes(origin) ? origin : undefined;
};

export default {
	async fetch(request, env, ctx): Promise<Response> {
		const allowedOrigins = parseAllowedOrigins(env.ALLOWED_ORIGINS);
		const resolveOrigin = (origin: string | null) =>
			resolveCorsOrigin(origin, allowedOrigins);

		const app = createAppflareHonoServer({
			db: getDatabase(env.MONGO_DB) as unknown as Db,
			corsOrigin: allowedOrigins,
			realtime: {
				durableObject: env.WEBSOCKET_HIBERNATION_SERVER,
				durableObjectName: "primary",
				notify: async (payload) => {
					const id = env.WEBSOCKET_HIBERNATION_SERVER.idFromName("primary");
					const stub = env.WEBSOCKET_HIBERNATION_SERVER.get(id);
					await stub.fetch("http://appflare-realtime/notify", {
						method: "POST",
						headers: { "content-type": "application/json" },
						body: JSON.stringify(payload),
					});
				},
			},
		}) as unknown as Hono<WorkerEnv>;

		app.use(
			"*",
			cors({
				origin: resolveOrigin,
				credentials: true,
				allowMethods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"],
				allowHeaders: ["Content-Type", "Authorization", "Cookie"],
				exposeHeaders: ["set-cookie"],
			})
		);

		const origin = request.headers.get("Origin");
		const allowedOrigin = resolveOrigin(origin);
		if (request.method === "OPTIONS") {
			return new Response(null, {
				status: 204,
				headers: {
					"Access-Control-Allow-Origin": allowedOrigin ?? "",
					"Access-Control-Allow-Credentials": "true",
					"Access-Control-Allow-Methods": "GET,POST,PUT,DELETE,OPTIONS",
					"Access-Control-Allow-Headers":
						request.headers.get("Access-Control-Request-Headers") ??
						"Content-Type, Authorization, Cookie",
					Vary: "Origin",
				},
			});
		}

		const upgradeHeader = request.headers.get("Upgrade");
		if (upgradeHeader === "websocket") {
			const url = new URL(request.url);
			if (url.pathname === "/ws") {
				const id = env.WEBSOCKET_HIBERNATION_SERVER.idFromName("primary");
				const stub = env.WEBSOCKET_HIBERNATION_SERVER.get(id);
				return stub.fetch(request);
			}
		}

		const response = await app.fetch(request, env, ctx);
		if (allowedOrigin) {
			response.headers.set("Access-Control-Allow-Origin", allowedOrigin);
			response.headers.set("Access-Control-Allow-Credentials", "true");
			response.headers.append("Vary", "Origin");
		}
		return response;
	},
} satisfies ExportedHandler<Env>;

export { MONGO_DURABLE_OBJECT, WebSocketHibernationServer };
`;
}
